# Generated by Django 2.1 on 2018-08-14 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='dep_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='menu_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='permission',
            old_name='permission_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='permission',
            old_name='permission_url',
            new_name='url',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='role_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='role',
            name='permissions_id',
        ),
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(to='rbac.Permission'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='roles',
            field=models.ManyToManyField(to='rbac.Role'),
        ),
    ]
