# Generated by Django 2.1 on 2018-08-14 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_auto_20180814_1230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='parent_id',
            new_name='parent',
        ),
    ]
