# Generated by Django 2.1 on 2018-08-14 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0003_auto_20180814_1323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permission',
            old_name='menu_id',
            new_name='menu',
        ),
    ]
