# Generated by Django 2.1 on 2018-08-17 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0005_auto_20180814_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='department',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='department',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rbac.Department'),
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='roles',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='roles',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rbac.Role'),
        ),
    ]
