# Generated by Django 2.1 on 2018-08-22 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0009_auto_20180817_2059'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=10, unique=True)),
                ('order_date', models.DateField(blank=True)),
                ('vin', models.CharField(max_length=17, unique=True)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_area', models.CharField(max_length=100)),
                ('payment_way', models.PositiveSmallIntegerField()),
                ('payment_nper', models.PositiveSmallIntegerField()),
                ('transaction_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('security_deposit', models.DecimalField(decimal_places=2, max_digits=8)),
                ('replacement_subsidy', models.DecimalField(decimal_places=2, max_digits=8)),
                ('gift_je', models.DecimalField(decimal_places=2, max_digits=8)),
                ('time_fee', models.DecimalField(decimal_places=2, max_digits=8)),
                ('navigation_4G_fee', models.DecimalField(decimal_places=2, max_digits=8)),
                ('charging_fee', models.DecimalField(decimal_places=2, max_digits=8)),
                ('first_payment', models.DecimalField(decimal_places=2, max_digits=9)),
                ('financial_advisory_fee', models.DecimalField(decimal_places=2, max_digits=8)),
                ('personal_accident_insurance', models.DecimalField(decimal_places=2, max_digits=8)),
                ('mortgage_fee', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fs_vps', models.DecimalField(decimal_places=2, max_digits=8)),
                ('labor_cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('ln_vps', models.DecimalField(decimal_places=2, max_digits=8)),
                ('free_mortgage_fee', models.DecimalField(decimal_places=2, max_digits=8)),
                ('installment_bond', models.DecimalField(decimal_places=2, max_digits=8)),
                ('glass_insurance', models.DecimalField(decimal_places=2, max_digits=8)),
                ('scratch_risk', models.DecimalField(decimal_places=2, max_digits=8)),
                ('theft_insurance', models.DecimalField(decimal_places=2, max_digits=8)),
                ('extension_insurance', models.DecimalField(decimal_places=2, max_digits=8)),
                ('listing_fee', models.DecimalField(decimal_places=2, max_digits=6)),
                ('value_added_package', models.DecimalField(decimal_places=2, max_digits=8)),
                ('maintenance_package', models.DecimalField(decimal_places=2, max_digits=8)),
                ('esc_potential_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('esc_procurement_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('earnest_money', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.PositiveSmallIntegerField()),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
                ('submit_date', models.DateTimeField(blank=True)),
                ('auditing_date', models.DateTimeField(blank=True)),
                ('settlement_date', models.DateTimeField(blank=True)),
                ('auditing_name', models.ForeignKey(on_delete=django.db.models.deletion.ProtectedError, related_name='auditing_UserInfo', to='rbac.UserInfo')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.ProtectedError, to='rbac.Department')),
                ('report_name', models.ForeignKey(on_delete=django.db.models.deletion.ProtectedError, related_name='report_UserInfo', to='rbac.UserInfo')),
                ('settlement_name', models.ForeignKey(on_delete=django.db.models.deletion.ProtectedError, related_name='settlement_UserInfo', to='rbac.UserInfo')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(max_length=17, unique=True)),
                ('six_yards', models.CharField(max_length=6)),
                ('vehicle_type', models.CharField(max_length=128)),
                ('guidance_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.PositiveSmallIntegerField(default=0)),
                ('storage_date', models.DateField(auto_now_add=True)),
                ('out_date', models.DateField(auto_now=True)),
                ('remarks', models.CharField(blank=True, max_length=128)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.ProtectedError, to='rbac.Department')),
            ],
            options={
                'db_table': 'wz_vehicle_info',
            },
        ),
        migrations.AddField(
            model_name='detailinfo',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rbac.VehicleInfo'),
        ),
    ]
