# Generated by Django 2.1 on 2018-08-25 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0011_auto_20180822_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleinfo',
            name='out_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
