# Generated by Django 2.1 on 2018-08-29 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0013_auto_20180829_1015'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='detailinfo',
            table='wz_detail_info',
        ),
        migrations.AlterModelTable(
            name='detailmaxno',
            table='wz_detail_maxno',
        ),
    ]
