# Generated by Django 2.1 on 2018-09-05 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0015_auto_20180829_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailinfo',
            name='vin',
        ),
        migrations.AlterField(
            model_name='detailinfo',
            name='auditing_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detailinfo',
            name='auditing_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.ProtectedError, related_name='auditing_UserInfo', to='rbac.UserInfo'),
        ),
        migrations.AlterField(
            model_name='detailinfo',
            name='order_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='detailinfo',
            name='payment_nper',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='detailinfo',
            name='payment_way',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='detailinfo',
            name='settlement_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detailinfo',
            name='settlement_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.ProtectedError, related_name='settlement_UserInfo', to='rbac.UserInfo'),
        ),
        migrations.AlterField(
            model_name='detailinfo',
            name='status',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='detailinfo',
            name='submit_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
