# Generated by Django 2.1 on 2018-09-05 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0016_auto_20180905_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailinfo',
            name='order_no',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
