# Generated by Django 2.1 on 2018-09-10 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0017_auto_20180905_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailinfo',
            name='bx_ysk_xj',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='detailinfo',
            name='deductions_xj',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='detailinfo',
            name='dkje_xx',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='detailinfo',
            name='jr_ysk_xj',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='detailinfo',
            name='lc_ysk_xj',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='detailinfo',
            name='skzj_xx',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='detailinfo',
            name='yp_ysk_xj',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='detailinfo',
            name='ysk_xx',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='detailinfo',
            name='zzb_ysk_xj',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
